spring:
  application:
    name: cramit
  profiles:
    active: local

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

server:
  port: 8080

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId}] %-5level %logger{36} - %msg%n"

resilience4j:
  timelimiter:
    instances:
      oauth:
        timeout-duration: 5s
      stt:
        timeout-duration: 30s
      gemini:
        timeout-duration: 20s
  retry:
    instances:
      oauth:
        max-attempts: 3
        wait-duration: 500ms
        enable-exponential-backoff: true
      stt:
        max-attempts: 3
        wait-duration: 500ms
        enable-exponential-backoff: true
      gemini:
        max-attempts: 3
        wait-duration: 500ms
        enable-exponential-backoff: true
  circuitbreaker:
    instances:
      oauth:
        sliding-window-size: 5
        minimum-number-of-calls: 5
        failure-rate-threshold: 100
        wait-duration-in-open-state: 60s
        permitted-number-of-calls-in-half-open-state: 1
      stt:
        sliding-window-size: 5
        minimum-number-of-calls: 5
        failure-rate-threshold: 100
        wait-duration-in-open-state: 60s
        permitted-number-of-calls-in-half-open-state: 1
      gemini:
        sliding-window-size: 5
        minimum-number-of-calls: 5
        failure-rate-threshold: 100
        wait-duration-in-open-state: 60s
        permitted-number-of-calls-in-half-open-state: 1
